baseURL: "http://example.org/"
languageCode: "en-us"
params:
  title: "Property for Sale"
  background: "#345282"
  bootstrap: "4.5.2"
markup:
  highlight:
    style: friendly
  goldmark:
    renderer:
      unsafe: true
